export const leaders = [
  {
    serial: '1',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '2',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '3',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '4',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '5',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '6',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '7',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '8',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '9',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
  {
    serial: '10',
    name: 'peanutbetter',
    avatar: require('../assets/icons/leader.png'),
    UDSC: '58',
    kills: '70',
  },
];
